### ISSUE TITLE
3.5.1 pack issue. should have been 3.5.1.1

### ISSUE THREAD

**Issue by infograf768** [seokjoon/joomla-lang-ko#1]
Please beware of the versions for 3.5.2.
 It should be version 3.5.2.1 in the pkg and other xml files. :smiley:
See http://forum.joomla.org/viewtopic.php?f=54&t=923389&p=3396919#p3396914
I uploaded for you a corrected pack to joomlacode (3.5.1.2)
http://joomlacode.org/gf/download/frsrelease/20256/163136/ko-KR_joomla_lang_full_3.5.1v2.zip

**Comment by seokjoon** [comment]
I'm sorry for my carelessness update. I fix it(https://github.com/seokjoon/joomla-lang-ko/commit/1bd94d3e34d1874430fea7e62bebac5704c5738a)
Thank you for your advice.

**Comment by infograf768** [comment]
No problem. If you have another updated pack for 3.5.2, do not forget to increase the xml version (3.5.2.2, 3.5.2.3, etc.)

**Comment by seokjoon** [comment]
Yes, I will not forget it. Thank you :)
